package Vista;

import Controlador.ControladorChat;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;

import java.util.Observable;
import java.util.Observer;

import modelo.Chat;

/**
 *
 * @author usuario
 */
public class PanelChat extends javax.swing.JPanel implements IVista,Observer
{
    private Observable chat;
    /** Creates new form PanelChat */
    public PanelChat()
    {
        this.setSize(500, 500);
        initComponents();
        this.BotonEnviar.setActionCommand(ControladorChat.ENVIAR);
        this.BotonCerrar.setActionCommand(ControladorChat.CERRAR);
        this.TextoConversacion.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        panel2 = new javax.swing.JPanel();
        textoYoEscribo = new javax.swing.JTextField();
        panelYo = new javax.swing.JPanel();
        labelYo = new javax.swing.JLabel();
        panelBotonEnviar = new javax.swing.JPanel();
        BotonEnviar = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        BotonCerrar = new javax.swing.JButton();
        labelChatWindows = new javax.swing.JLabel();
        panelConversacion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoConversacion = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 255, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(470, 470));
        setMinimumSize(new java.awt.Dimension(470, 470));
        setPreferredSize(new java.awt.Dimension(470, 470));

        textoYoEscribo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                textoYoEscriboKeyPressed(evt);
            }
        });

        panelYo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null));
        panelYo.setLayout(new java.awt.BorderLayout());

        labelYo.setText("Yo:");
        panelYo.add(labelYo, java.awt.BorderLayout.CENTER);

        panelBotonEnviar.setBackground(new java.awt.Color(255, 102, 102));

        BotonEnviar.setText("Enviar");

        javax.swing.GroupLayout panelBotonEnviarLayout = new javax.swing.GroupLayout(panelBotonEnviar);
        panelBotonEnviar.setLayout(panelBotonEnviarLayout);
        panelBotonEnviarLayout.setHorizontalGroup(
            panelBotonEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonEnviarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotonEnviarLayout.setVerticalGroup(
            panelBotonEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonEnviarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonEnviar))
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelYo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(panelBotonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoYoEscribo, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelYo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoYoEscribo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(panelBotonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        BotonCerrar.setText("Cerrar Chat");

        labelChatWindows.setText("Chat Windows");

        panelConversacion.setBackground(new java.awt.Color(204, 255, 204));
        panelConversacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null));

        TextoConversacion.setColumns(20);
        TextoConversacion.setRows(5);
        jScrollPane1.setViewportView(TextoConversacion);

        javax.swing.GroupLayout panelConversacionLayout = new javax.swing.GroupLayout(panelConversacion);
        panelConversacion.setLayout(panelConversacionLayout);
        panelConversacionLayout.setHorizontalGroup(
            panelConversacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConversacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelConversacionLayout.setVerticalGroup(
            panelConversacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConversacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConversacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelChatWindows, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonCerrar)
                .addGap(85, 85, 85))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(labelChatWindows)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(BotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelConversacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }//GEN-END:initComponents

    private void textoYoEscriboKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoYoEscriboKeyPressed
    {//GEN-HEADEREND:event_textoYoEscriboKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            this.BotonEnviar.doClick();
    }//GEN-LAST:event_textoYoEscriboKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JButton BotonEnviar;
    private javax.swing.JTextArea TextoConversacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelChatWindows;
    private javax.swing.JLabel labelYo;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panelBotonEnviar;
    private javax.swing.JPanel panelConversacion;
    private javax.swing.JPanel panelYo;
    private javax.swing.JTextField textoYoEscribo;
    // End of variables declaration//GEN-END:variables

    /* public JButton getBoton()
    {
        return this.BotonEnviar;
    } */
    @Override
    public void addActionListener(ActionListener a)
    {
        this.BotonEnviar.addActionListener(a);
        this.BotonCerrar.addActionListener(a);
    }
    
    public Chat getChat()
    {
        return (Chat)this.chat;
    }
    
    public String getMensaje()
    {
        return this.textoYoEscribo.getText();
    }
    
    public void añadirObservable(Observable chat)
    {
        this.chat=chat;
        chat.addObserver(this);
    }
    
    public void update(Observable obs,Object o)
    {
        String cartel=(String)o;
        if (this.chat==obs)
        {
            if (cartel.equals(Chat.CERRAR))
                this.BotonCerrar.doClick();
            else
                this.TextoConversacion.append(cartel + "\n");
        }
        else
            throw new IllegalArgumentException();
    }
}
